version: '3.3'
services:
  nginx:
    build:
      context: ../../dockerfiles/nginx
      dockerfile: Dockerfile
    command: sh /home/scripts/start.sh
    volumes:
      - ../nginx/nginx_config_dev.conf:/etc/nginx/conf.d/default.conf
      - ../../app:/var/www/html
      - ../scripts/nginx:/home/scripts
    ports:
      - 80:80
  nodejs:
    build:
      context: ../../dockerfiles/nodejs
      dockerfile: Dockerfile
    volumes:
      - ../../app:/home/app
      - ../scripts/nodejs:/home/scripts
    ports:
      - 2000:2000
    command: sh /home/scripts/start.sh
networks:
  default:
    external:
      name: dockernet